title: Fraud Detection in Ethereum Transaction Networks
description: A comparison of graph-based and non-graph based deep learning approaches to fraud detection utilizing TigerGraph.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman